How to Build SDL for QNX7
Ford-Luxoft/sdl_core pull request #18
Opened 2019-01-15 12:53 UTC by BSolonenko

This PR is **ready** for review.  
This PR includes implementation for  proposal [Porting SDL to QNX700 and Automotive Grade Linux (AGL) x64 platforms](https://github.com/LuxoftAKutsan/sdl_evolution/blob/port_sdl_on_qnx700_and_agl/proposals/nnnn-sdl_on_qnx700_agl.md)

### Summary
SDL build instruction for QNX7 has been added.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2019-01-15 13:08 UTC, AKalinich-Luxoft approved these changes

2019-01-15 13:18 UTC, LuxoftAKutsan requested changes

2019-01-15 13:18 UTC, LuxoftAKutsan commented on README.md
> +myQNX -> Download QNX SDP 7.0 today -> QNX Software Center -> QNX Software Center 1.3.1 Build 201808201144 - Linux Hosts
This details redundant

2019-01-15 13:18 UTC, LuxoftAKutsan commented on README.md
> +
Also redundant

2019-01-15 13:18 UTC, LuxoftAKutsan commented on README.md
> +2. Clone sdl_core repository
Cloning is not related to compiling.

2019-01-15 13:18 UTC, LuxoftAKutsan commented on README.md
> +mkdir <path_to_build_folder>/<build_folder_name>
What is path to build folder and build folder name? What is the difference?

2019-01-15 13:18 UTC, LuxoftAKutsan commented on README.md
> +2. Open the  Tab "Manage Installation" -> Tab "Available"
Please remove so detailed staff. Let people care where to get qnx image or hardware

2019-01-15 13:18 UTC, LuxoftAKutsan commented on README.md
> +1. Install QNX7 SDP into `/opt/qnx700` using QNX Software Center (with [myQNX account](https://www.qnx.com/account))
Opt/qnx700 is not mandatory path

2019-01-15 13:18 UTC, LuxoftAKutsan commented on README.md
> +3. In the image, run `smartDeviceLinkCore` which is located in the bin folder
Add chapter How to run unit tests

2019-01-17 07:42 UTC, SNiukalov approved these changes

2019-01-17 15:02 UTC, mkorniichuk requested changes

2019-01-17 15:02 UTC, mkorniichuk commented on README.md
> +mkdir <path_to_3rd_party_folder>/<3rd_party_folder_name>
@BSolonenko redundant step

2019-01-17 15:02 UTC, mkorniichuk commented on README.md
> +```bash
@BSolonenko why exactly bash?

2019-01-17 15:02 UTC, mkorniichuk commented on README.md
> +cmake -DCMAKE_TOOLCHAIN_FILE=<path_to_sdl_core>/toolchains/Toolchain-QNX7-ACC-x86.cmake <path_to_sdl>
@BSolonenko so **path_to_sdl** or **path_to_sdl_core**?

2019-01-18 10:34 UTC, vkushnirenko-luxoft commented
AGL_build

2019-02-19 11:31 UTC, closed without merging