Script to run tests has been added.
Ford-Luxoft/sdl_core pull request #20
Opened 2019-01-18 17:03 UTC by BSolonenko

This PR is **ready** for review.  
This PR includes implementation for  proposal [Porting SDL to QNX700 and Automotive Grade Linux (AGL) x64 platforms](https://github.com/LuxoftAKutsan/sdl_evolution/blob/port_sdl_on_qnx700_and_agl/proposals/nnnn-sdl_on_qnx700_agl.md)

### Summary
Script to run tests has been added.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2019-01-21 08:22 UTC, AKalinich-Luxoft requested changes

2019-01-21 08:22 UTC, AKalinich-Luxoft commented on tools/infrastructure/run_tests.sh
> +#/bin/bash
@BSolonenko please insert copyright comment here

2019-01-21 08:22 UTC, AKalinich-Luxoft commented on tools/infrastructure/run_tests.sh
> +    echo "      Start $cur_test: $testname"
@BSolonenko why so many spaces here?

2019-01-21 08:22 UTC, AKalinich-Luxoft commented on tools/infrastructure/run_tests.sh
> +run_all_test() {
@BSolonenko `run_all_tests`

2019-01-21 08:22 UTC, AKalinich-Luxoft commented on tools/infrastructure/run_tests.sh
> +exit $failed_test
@BSolonenko where this variable comes from?

2019-01-21 08:32 UTC, BSolonenko commented on tools/infrastructure/run_tests.sh
> +exit $failed_test
@AKalinich-Luxoft from here  https://github.com/Ford-Luxoft/sdl_core/blob/1d0f826f681dc9e8aa813d8721e190dcf28193d2/tools/infrastructure/run_tests.sh#L65

2019-01-21 08:32 UTC, BSolonenko commented on tools/infrastructure/run_tests.sh
> +run_all_test() {
@AKalinich-Luxoft fixed in https://github.com/Ford-Luxoft/sdl_core/pull/20/commits/1d0f826f681dc9e8aa813d8721e190dcf28193d2

2019-01-21 08:32 UTC, BSolonenko commented on tools/infrastructure/run_tests.sh
> +#/bin/bash
@AKalinich-Luxoft fixed in https://github.com/Ford-Luxoft/sdl_core/pull/20/commits/1d0f826f681dc9e8aa813d8721e190dcf28193d2

2019-01-21 08:34 UTC, BSolonenko commented on tools/infrastructure/run_tests.sh
> +    echo "      Start $cur_test: $testname"
@AKalinich-Luxoft for beautiful formatted output

2019-01-21 08:38 UTC, AKalinich-Luxoft commented on tools/infrastructure/run_tests.sh
> +exit $failed_test
@BSolonenko but its name `failed_test_count`. Shouldn't it have the same name here?

2019-01-21 09:05 UTC, LuxoftAKutsan requested changes

2019-01-21 09:05 UTC, LuxoftAKutsan commented on tools/CMakeLists.txt
> +  file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/infrastructure/run_tests.sh DESTINATION ${CMAKE_INSTALL_PREFIX}/TestBin)
@BSolonenko rename test bin folder just to `tests`

2019-01-21 09:05 UTC, LuxoftAKutsan commented on tools/infrastructure/run_tests.sh
> +#/bin/bash
@BSolonenko shebang has  wrong syntax

2019-01-21 09:40 UTC, vkushnirenko-luxoft commented
AGL_build

2019-01-21 09:57 UTC, BSolonenko commented on tools/infrastructure/run_tests.sh
> +exit $failed_test
@AKalinich-Luxoft fixed in https://github.com/Ford-Luxoft/sdl_core/pull/20/commits/59e939193d3522070bc8c6c20851b0c84c4dc769

2019-01-21 09:57 UTC, BSolonenko commented on tools/CMakeLists.txt
> +  file(COPY ${CMAKE_CURRENT_SOURCE_DIR}/infrastructure/run_tests.sh DESTINATION ${CMAKE_INSTALL_PREFIX}/TestBin)
@LuxoftAKutsan fixed in https://github.com/Ford-Luxoft/sdl_core/pull/20/commits/96767fb7d769b39a6f450da09cb510c68d6a838a

2019-01-21 10:23 UTC, AKalinich-Luxoft approved these changes

2019-01-21 11:07 UTC, mkorniichuk requested changes

2019-01-21 11:07 UTC, mkorniichuk commented on tools/infrastructure/run_tests.sh
> +
@BSolonenko, pretty hard to understand which arguments I can use with this script. I would add some comments, usage example, etc. Also, I would advise making global vars for command-line args in the very beginning of a script.

2019-01-21 11:07 UTC, mkorniichuk commented on tools/infrastructure/run_tests.sh
> +dir=`pwd`
@BSolonenko, not the best solution, I believe. Please, consider the usage of extra argument to set the tests directory.

2019-01-21 11:07 UTC, mkorniichuk commented on tools/infrastructure/run_tests.sh
> +    for i in $tests; do
@BSolonenko usage of **i** as index would exclude **cur_test** variable

2019-01-21 11:07 UTC, mkorniichuk commented on tools/infrastructure/run_tests.sh
> +        if [[ $test_result -ne 0 ]]; then
@BSolonenko, just a suggestion, but do you think, usage of **test_result** outside of **run_test()** is a good idea?

2019-01-21 11:07 UTC, mkorniichuk commented on tools/infrastructure/run_tests.sh
> +    cur_test_test_count=`echo $cur_test/$test_count | sed -r ':l;/.{5}/q;s/.*/& /;bl'`
@BSolonenko I believe, this could be used in **run_all_tests()**, since, as for me, **cur_test** and **test_count** should not be used in a function supposed to run a single test.

2019-01-21 11:07 UTC, mkorniichuk commented on tools/infrastructure/run_tests.sh
> +        if [[ $4 == "-L" ]]; then
@BSolonenko  as for me **-L** not the best key for verbose output. Please, consider **-V** or **--verbose** flags

2019-01-21 11:07 UTC, mkorniichuk commented on tools/infrastructure/run_tests.sh
> +    fullpathname=${full_test_name%/*}
@BSolonenko Why the name of the variable is not underscore separated?

2019-01-21 11:07 UTC, mkorniichuk commented on tools/infrastructure/run_tests.sh
> +    cur_dir=$PWD
@BSolonenko why not to use it as a global variable, since you do the same in **dir=`pwd`**?

2019-01-21 13:43 UTC, BSolonenko commented
@mkorniichuk fixed in https://github.com/Ford-Luxoft/sdl_core/pull/20/commits/64dafdf75dbd9d4ef2008f96320268618357369a

2019-01-21 17:32 UTC, vkushnirenko-luxoft commented
AGL_build

2019-01-22 07:25 UTC, SNiukalov approved these changes

2019-01-22 08:35 UTC, LuxoftAKutsan approved these changes

2019-01-22 08:54 UTC, mkorniichuk approved these changes

2019-01-22 09:36 UTC, BSolonenko commented
QNX7_build

2019-01-22 10:34 UTC, AByzhynar requested changes

2019-01-22 10:34 UTC, AByzhynar commented on tools/infrastructure/run_tests.sh
> +
@BSolonenko Also add please option `-h` ( `--help` ) which shows usage

2019-01-23 12:45 UTC, BSolonenko commented
@AByzhynar option -h ( --help ) added in https://github.com/Ford-Luxoft/sdl_core/pull/20/commits/ef20d709741d0aa11d17bc10d4925d8a0b3bec4c

2019-01-23 15:44 UTC, AByzhynar approved these changes

2019-01-23 16:25 UTC, merged