Refactoring c make lists for unit tests
Ford-Luxoft/sdl_core pull request #3
Opened 2018-12-11 08:35 UTC by BSolonenko

This PR is **[ready]** for review.

### Risk
This PR makes **[no]** API changes.

### Summary
These changes include next tests into a build: 
- config_profile_test
- connection_handler_test
- formatters_test
- hmi_message_handler_test
- media_manager_test
- protocol_handler_test
- resumption_test
- rpc_base_test
- security_manager_test
- smart_object_test
- telemetry_monitor_test
- transport_manager_test

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2018-12-11 08:41 UTC, BSolonenko commented
@AKalinich-Luxoft @AByzhynar @LuxoftAKutsan @SNiukalov Please review this PR.

2019-01-02 11:30 UTC, LuxoftAKutsan approved these changes

2019-01-22 10:11 UTC, mkorniichuk requested changes

2019-01-22 10:11 UTC, mkorniichuk commented on src/components/transport_manager/test/CMakeLists.txt
> +if(BUILD_USB_SUPPORT)
@BSolonenko maybe use single if?

2019-01-22 10:11 UTC, mkorniichuk commented on src/components/transport_manager/test/CMakeLists.txt
> +               ${CMAKE_CURRENT_LIST_DIR}/network_interface_listener_test.cc
@BSolonenko Why not to use **collect_sources**?

2019-01-22 10:11 UTC, mkorniichuk commented on src/components/telemetry_monitor/test/CMakeLists.txt
> +               ${CMAKE_CURRENT_LIST_DIR}/application_manager_metric_test.cc
@BSolonenko I believe, **collect_sources** would help

2019-01-22 10:11 UTC, mkorniichuk commented on src/components/security_manager/test/CMakeLists.txt
> +  file(COPY ${CERT_ENTRY} DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
@BSolonenko have you tried to pass a list as an argument?

2019-01-22 10:11 UTC, mkorniichuk commented on src/components/config_profile/test/CMakeLists.txt
> +file(COPY smartDeviceLink.ini DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
@BSolonenko how about *.ini?

2019-01-31 10:26 UTC, AByzhynar requested changes

2019-01-31 10:26 UTC, AByzhynar commented on src/components/config_profile/test/CMakeLists.txt
> +     ${CMAKE_CURRENT_BINARY_DIR})
@BSolonenko Why did you divide copying of all files to separate functions?

2019-01-31 10:31 UTC, AByzhynar requested changes

2019-01-31 10:31 UTC, AByzhynar commented on src/components/config_profile/test/CMakeLists.txt
> +# Copyright (c) 2018, Ford Motor Company All rights reserved.
@BSolonenko 2019, isn't it?

2019-01-31 10:31 UTC, AByzhynar commented on src/components/connection_handler/test/CMakeLists.txt
> +# Copyright (c) 2018, Ford Motor Company All rights reserved.
@BSolonenko 2019, isn't it?

2019-01-31 10:31 UTC, AByzhynar commented on src/components/formatters/test/CMakeLists.txt
> +# Copyright (c) 2018, Ford Motor Company All rights reserved.
@BSolonenko 2019, isn't it?

2019-04-17 12:14 UTC, closed without merging